### ISSUE TITLE
PSQLException: ERROR: value too long for type character varying(255)

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/junit-sql-storage-plugin#41]
When I try to use the SQL storage engine I get the following error:

```
12:37:33  hudson.remoting.ProxyException: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
12:37:33  	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
12:37:33  	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
12:37:33  	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
12:37:33  	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
12:37:33  	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
12:37:33  	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
12:37:33  	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
12:37:33  	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
12:37:33  	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
12:37:33  	at io.jenkins.plugins.junit.storage.database.DatabaseTestResultStorage$RemotePublisherImpl.publish(DatabaseTestResultStorage.java:642)
12:37:33  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from de08-lz025.bbmag.bbraun.com/172.23.8.78:41788
12:37:33  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
12:37:33  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
12:37:33  		at hudson.remoting.Channel.call(Channel.java:1001)
12:37:33  		at hudson.FilePath.act(FilePath.java:1070)
12:37:33  		at hudson.FilePath.act(FilePath.java:1059)
12:37:33  		at hudson.tasks.junit.JUnitParser.summarizeResult(JUnitParser.java:113)
12:37:33  		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)
12:37:33  		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:52)
12:37:33  		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:25)
12:37:33  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
12:37:33  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
12:37:33  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:37:33  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:37:33  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:37:33  		at java.base/java.lang.Thread.run(Thread.java:834)
12:37:33  Caused: hudson.remoting.ProxyException: java.io.IOException: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
12:37:33  	at io.jenkins.plugins.junit.storage.database.DatabaseTestResultStorage$RemotePublisherImpl.publish(DatabaseTestResultStorage.java:649)
12:37:33  	at hudson.tasks.junit.JUnitParser$StorageParseResultCallable.handle(JUnitParser.java:188)
12:37:33  	at hudson.tasks.junit.JUnitParser$StorageParseResultCallable.handle(JUnitParser.java:175)
12:37:33  	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:155)
12:37:33  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3122)
12:37:33  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
12:37:33  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:37:33  	at hudson.remoting.Request$2.run(Request.java:369)
12:37:33  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
12:37:33  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:37:33  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:37:33  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:37:33  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
12:37:33  	at java.base/java.lang.Thread.run(Thread.java:834)
```

I don't see which value is larger then 255 characters in my test, but you should truncate all strings to 255 characters and log a warning if this happens.

Kind regards,
Michael

**Comment by timja** [comment]
Thanks, yeah I can't see either, probably best to make it a bit bigger.

**Comment by timja** [comment]
Any chance you can test with https://github.com/jenkinsci/junit-sql-storage-plugin/pull/42 @reitzmichnicht,

you can also just apply the sql change yourself to test it.
